ALTER TABLE TD_REMINDINFO 
    DROP CONSTRAINT TD_REMINDINFO_FK_1;
        
ALTER TABLE TD_SD_NOTEPAPER 
    DROP CONSTRAINT TD_SD_NOTEPAPER_FK_1;
        
ALTER TABLE TD_SD_NOTIC 
    DROP CONSTRAINT TD_SD_NOTIC_FK_1;
        
ALTER TABLE TD_SD_NOTIC 
    DROP CONSTRAINT TD_SD_NOTIC_FK_2;
        
ALTER TABLE TD_SD_RATIFYADVICE 
    DROP CONSTRAINT TD_SD_RATIFYADVICE_FK_1;
        
ALTER TABLE TD_SD_RATIFYADVICE 
    DROP CONSTRAINT TD_SD_RATIFYADVICE_FK_2;
        
ALTER TABLE TD_SD_REMIND 
    DROP CONSTRAINT TD_SD_REMIND_FK_1;
        
ALTER TABLE TD_SD_SHARE 
    DROP CONSTRAINT TD_SD_SHARE_FK_1;
        
ALTER TABLE TD_SD_SHARE 
    DROP CONSTRAINT TD_SD_SHARE_FK_2;
        
ALTER TABLE TD_SM_DICTDATA 
    DROP CONSTRAINT TD_SM_DICTDATA_FK_1;
        
ALTER TABLE TD_SM_DICTKEYWORDS 
    DROP CONSTRAINT TD_SM_DICTKEYWORDS_FK_1;
        
ALTER TABLE TD_SM_GROUPROLE 
    DROP CONSTRAINT TD_SM_GROUPROLE_FK_1;
        
ALTER TABLE TD_SM_LOGDETAIL 
    DROP CONSTRAINT TD_SM_LOGDETAIL_FK_1;
        
ALTER TABLE TD_SM_LOGDETAIL_HIS 
    DROP CONSTRAINT TD_SM_LOGDETAIL_HIS_FK_1;
        
ALTER TABLE TD_SM_ORGJOB 
    DROP CONSTRAINT TD_SM_ORGJOB_FK_1;
        
ALTER TABLE TD_SM_ORGJOBROLE 
    DROP CONSTRAINT TD_SM_ORGJOBROLE_FK_1;
        
ALTER TABLE TD_SM_ORGJOBROLE 
    DROP CONSTRAINT TD_SM_ORGJOBROLE_FK_2;
        
ALTER TABLE TD_SM_ORGJOBROLE 
    DROP CONSTRAINT TD_SM_ORGJOBROLE_FK_3;
        
ALTER TABLE TD_SM_ORGMANAGER 
    DROP CONSTRAINT TD_SM_ORGMANAGER_FK_1;
        
ALTER TABLE TD_SM_ORGMANAGER 
    DROP CONSTRAINT TD_SM_ORGMANAGER_FK_2;
        
ALTER TABLE TD_SM_ORGROLE 
    DROP CONSTRAINT TD_SM_ORGROLE_FK_1;
        
ALTER TABLE TD_SM_ORGUSER 
    DROP CONSTRAINT TD_SM_ORGUSER_FK_1;
        
ALTER TABLE TD_SM_ORGUSER 
    DROP CONSTRAINT TD_SM_ORGUSER_FK_2;
        
ALTER TABLE TD_SM_TAXCODE_ORGANIZATION 
    DROP CONSTRAINT TD_SM_TAXCODE_ORGANIZATIO_FK_1;
        
ALTER TABLE TD_SM_TAXCODE_ORGANIZATION 
    DROP CONSTRAINT TD_SM_TAXCODE_ORGANIZATIO_FK_2;
        
ALTER TABLE TD_SM_USERJOBORG 
    DROP CONSTRAINT TD_SM_USERJOBORG_FK_1;
        
ALTER TABLE TD_SM_USERROLE 
    DROP CONSTRAINT TD_SM_USERROLE_FK_1;
        
ALTER TABLE TD_SP_HOLIDAY 
    DROP CONSTRAINT TD_SP_HOLIDAY_FK_1;
        
ALTER TABLE TD_SD_SCHEDULAR 
    DROP CONSTRAINT TD_SD_SCHEDULAR_FK_1;
        
ALTER TABLE TD_SD_SCHEDULAR 
    DROP CONSTRAINT TD_SD_SCHEDULAR_FK_2;
        
ALTER TABLE TD_SM_DICTTYPE 
    DROP CONSTRAINT TD_SM_DICTTYPE_FK_1;
        

-----------------------------------------------------------------------------
-- TD_REMINDINFO
-----------------------------------------------------------------------------
DROP TABLE TD_REMINDINFO CASCADE CONSTRAINTS;

CREATE TABLE TD_REMINDINFO
(
    ID NUMBER(22) NOT NULL,
    TIME DATE,
    TYPE VARCHAR2(255),
    SOURCE VARCHAR2(255),
    CONTENT VARCHAR2(1000),
    USER_ID NUMBER(22)
);

ALTER TABLE TD_REMINDINFO
    ADD CONSTRAINT TD_REMINDINFO_PK
PRIMARY KEY (ID);






-----------------------------------------------------------------------------
-- TD_SD_NOTEPAPER
-----------------------------------------------------------------------------
DROP TABLE TD_SD_NOTEPAPER CASCADE CONSTRAINTS;

CREATE TABLE TD_SD_NOTEPAPER
(
    NOTEPAPER_ID NUMBER(22) NOT NULL,
    TIME DATE,
    CONTENT VARCHAR2(1024),
    USER_ID NUMBER(22)
);

ALTER TABLE TD_SD_NOTEPAPER
    ADD CONSTRAINT TD_SD_NOTEPAPER_PK
PRIMARY KEY (NOTEPAPER_ID);






-----------------------------------------------------------------------------
-- TD_SD_NOTIC
-----------------------------------------------------------------------------
DROP TABLE TD_SD_NOTIC CASCADE CONSTRAINTS;

CREATE TABLE TD_SD_NOTIC
(
    CONTENT VARCHAR2(1000),
    BEGINTIME DATE,
    ENDTIME DATE,
    PLACE VARCHAR2(255),
    EXECUTOR_ID NUMBER(22),
    NOTIC_ID NUMBER(22) NOT NULL,
    STATUS NUMBER(22) default 0,
    TOPIC VARCHAR2(255),
    SOURCE VARCHAR2(255),
    NOTIC_PLANNER_ID NUMBER(22)
);

ALTER TABLE TD_SD_NOTIC
    ADD CONSTRAINT TD_SD_NOTIC_PK
PRIMARY KEY (NOTIC_ID);






-----------------------------------------------------------------------------
-- TD_SD_RATIFYADVICE
-----------------------------------------------------------------------------
DROP TABLE TD_SD_RATIFYADVICE CASCADE CONSTRAINTS;

CREATE TABLE TD_SD_RATIFYADVICE
(
    SCHEDULAR_ID NUMBER(22),
    RATIFIER_ID NUMBER(22),
    ADVICE VARCHAR2(1000),
    RATIFYADVICE_ID NUMBER(22) NOT NULL
);

ALTER TABLE TD_SD_RATIFYADVICE
    ADD CONSTRAINT TD_SD_RATIFYADVICE_PK
PRIMARY KEY (RATIFYADVICE_ID);






-----------------------------------------------------------------------------
-- TD_SD_REMIND
-----------------------------------------------------------------------------
DROP TABLE TD_SD_REMIND CASCADE CONSTRAINTS;

CREATE TABLE TD_SD_REMIND
(
    REMIND_ID NUMBER(22) NOT NULL,
    ISSYSTEM NUMBER(22),
    ISEMAIL NUMBER(22),
    ISMESSAGE NUMBER(22),
    SCHEDULAR_ID NUMBER(22),
    REMIND_BEGIN_TIME DATE,
    REMIND_END_TIME DATE,
    INTERVAL_TIME NUMBER(22),
    INTERVALTYPE NUMBER(22),
    TRIGGERTYPE NUMBER(22) default 0,
    CRON_TIME VARCHAR2(255)
);

ALTER TABLE TD_SD_REMIND
    ADD CONSTRAINT TD_SD_REMIND_PK
PRIMARY KEY (REMIND_ID);






-----------------------------------------------------------------------------
-- TD_SD_SHARE
-----------------------------------------------------------------------------
DROP TABLE TD_SD_SHARE CASCADE CONSTRAINTS;

CREATE TABLE TD_SD_SHARE
(
    VIEWUSER_ID NUMBER(22) NOT NULL,
    SCHEDULAR_ID NUMBER(22) NOT NULL
);

ALTER TABLE TD_SD_SHARE
    ADD CONSTRAINT TD_SD_SHARE_PK
PRIMARY KEY (VIEWUSER_ID,SCHEDULAR_ID);






-----------------------------------------------------------------------------
-- TD_SM_DICTDATA
-----------------------------------------------------------------------------
DROP TABLE TD_SM_DICTDATA CASCADE CONSTRAINTS;

CREATE TABLE TD_SM_DICTDATA
(
    DICTDATA_ID VARCHAR2(50) NOT NULL,
    DICTTYPE_ID VARCHAR2(50),
    DICTDATA_NAME VARCHAR2(100),
    DICTDATA_VALUE VARCHAR2(100),
    DICTDATA_ORDER NUMBER(10) default 0
);

ALTER TABLE TD_SM_DICTDATA
    ADD CONSTRAINT TD_SM_DICTDATA_PK
PRIMARY KEY (DICTDATA_ID);






-----------------------------------------------------------------------------
-- TD_SM_DICTKEYWORDS
-----------------------------------------------------------------------------
DROP TABLE TD_SM_DICTKEYWORDS CASCADE CONSTRAINTS;

CREATE TABLE TD_SM_DICTKEYWORDS
(
    KEYWORD_ID NUMBER(10) NOT NULL,
    DICTTYPE_ID VARCHAR2(50),
    FILED_NAME VARCHAR2(50),
    JAVA_PROPERTY VARCHAR2(50)
);

ALTER TABLE TD_SM_DICTKEYWORDS
    ADD CONSTRAINT TD_SM_DICTKEYWORDS_PK
PRIMARY KEY (KEYWORD_ID);






-----------------------------------------------------------------------------
-- TD_SM_GROUPROLE
-----------------------------------------------------------------------------
DROP TABLE TD_SM_GROUPROLE CASCADE CONSTRAINTS;

CREATE TABLE TD_SM_GROUPROLE
(
    GROUP_ID NUMBER(22) NOT NULL,
    ROLE_ID VARCHAR2(50) NOT NULL,
    RESOP_ORIGIN_USERID VARCHAR2(50) default '1'
);

ALTER TABLE TD_SM_GROUPROLE
    ADD CONSTRAINT TD_SM_GROUPROLE_PK
PRIMARY KEY (GROUP_ID,ROLE_ID);






-----------------------------------------------------------------------------
-- TD_SM_LOGDETAIL
-----------------------------------------------------------------------------
DROP TABLE TD_SM_LOGDETAIL CASCADE CONSTRAINTS;

CREATE TABLE TD_SM_LOGDETAIL
(
    DETAIL_ID NUMBER(10) NOT NULL,
    OPER_TABLE VARCHAR2(50),
    LOG_ID NUMBER(22),
    OP_KEY_ID VARCHAR2(50),
    DETAIL_CONTENT CLOB,
    OP_TYPE NUMBER(1)
);

ALTER TABLE TD_SM_LOGDETAIL
    ADD CONSTRAINT TD_SM_LOGDETAIL_PK
PRIMARY KEY (DETAIL_ID);






-----------------------------------------------------------------------------
-- TD_SM_LOGDETAIL_HIS
-----------------------------------------------------------------------------
DROP TABLE TD_SM_LOGDETAIL_HIS CASCADE CONSTRAINTS;

CREATE TABLE TD_SM_LOGDETAIL_HIS
(
    DETAIL_ID NUMBER(10) NOT NULL,
    OPER_TABLE VARCHAR2(50),
    LOG_ID NUMBER(22),
    OP_KEY_ID VARCHAR2(50),
    DETAIL_CONTENT CLOB,
    OP_TYPE NUMBER(1)
);

ALTER TABLE TD_SM_LOGDETAIL_HIS
    ADD CONSTRAINT TD_SM_LOGDETAIL_HIS_PK
PRIMARY KEY (DETAIL_ID);






-----------------------------------------------------------------------------
-- TD_SM_ORGJOB
-----------------------------------------------------------------------------
DROP TABLE TD_SM_ORGJOB CASCADE CONSTRAINTS;

CREATE TABLE TD_SM_ORGJOB
(
    ORG_ID VARCHAR2(50) NOT NULL,
    JOB_ID VARCHAR2(50) NOT NULL,
    JOB_SN NUMBER(22)
);

ALTER TABLE TD_SM_ORGJOB
    ADD CONSTRAINT TD_SM_ORGJOB_PK
PRIMARY KEY (ORG_ID,JOB_ID);






-----------------------------------------------------------------------------
-- TD_SM_ORGJOBROLE
-----------------------------------------------------------------------------
DROP TABLE TD_SM_ORGJOBROLE CASCADE CONSTRAINTS;

CREATE TABLE TD_SM_ORGJOBROLE
(
    ORG_ID VARCHAR2(50) NOT NULL,
    JOB_ID VARCHAR2(50) NOT NULL,
    ROLE_ID VARCHAR2(50) NOT NULL,
    RESOP_ORIGIN_USERID VARCHAR2(50) default '1'
);

ALTER TABLE TD_SM_ORGJOBROLE
    ADD CONSTRAINT TD_SM_ORGJOBROLE_PK
PRIMARY KEY (ORG_ID,JOB_ID,ROLE_ID);






-----------------------------------------------------------------------------
-- TD_SM_ORGMANAGER
-----------------------------------------------------------------------------
DROP TABLE TD_SM_ORGMANAGER CASCADE CONSTRAINTS;

CREATE TABLE TD_SM_ORGMANAGER
(
    USER_ID NUMBER(22) NOT NULL,
    ORG_ID VARCHAR2(50) NOT NULL
);

ALTER TABLE TD_SM_ORGMANAGER
    ADD CONSTRAINT TD_SM_ORGMANAGER_PK
PRIMARY KEY (USER_ID,ORG_ID);






-----------------------------------------------------------------------------
-- TD_SM_ORGROLE
-----------------------------------------------------------------------------
DROP TABLE TD_SM_ORGROLE CASCADE CONSTRAINTS;

CREATE TABLE TD_SM_ORGROLE
(
    ORG_ID VARCHAR2(50) NOT NULL,
    ROLE_ID VARCHAR2(50) NOT NULL,
    RESOP_ORIGIN_USERID VARCHAR2(50) default '1'
);

ALTER TABLE TD_SM_ORGROLE
    ADD CONSTRAINT TD_SM_ORGROLE_PK
PRIMARY KEY (ORG_ID,ROLE_ID);






-----------------------------------------------------------------------------
-- TD_SM_ORGUSER
-----------------------------------------------------------------------------
DROP TABLE TD_SM_ORGUSER CASCADE CONSTRAINTS;

CREATE TABLE TD_SM_ORGUSER
(
    ORG_ID VARCHAR2(50) NOT NULL,
    USER_ID NUMBER(22) NOT NULL
);

ALTER TABLE TD_SM_ORGUSER
    ADD CONSTRAINT TD_SM_ORGUSER_PK
PRIMARY KEY (USER_ID);






-----------------------------------------------------------------------------
-- TD_SM_TAXCODE_ORGANIZATION
-----------------------------------------------------------------------------
DROP TABLE TD_SM_TAXCODE_ORGANIZATION CASCADE CONSTRAINTS;

CREATE TABLE TD_SM_TAXCODE_ORGANIZATION
(
    ORG_ID VARCHAR2(50) NOT NULL,
    DICTTYPE_ID VARCHAR2(50) NOT NULL,
    DATA_VALUE VARCHAR2(100) NOT NULL,
    OPCODE VARCHAR2(10) NOT NULL,
    DATA_NAME VARCHAR2(100)
);

ALTER TABLE TD_SM_TAXCODE_ORGANIZATION
    ADD CONSTRAINT TD_SM_TAXCODE_ORGANIZATION_PK
PRIMARY KEY (ORG_ID,DICTTYPE_ID,DATA_VALUE,OPCODE);






-----------------------------------------------------------------------------
-- TD_SM_USERJOBORG
-----------------------------------------------------------------------------
DROP TABLE TD_SM_USERJOBORG CASCADE CONSTRAINTS;

CREATE TABLE TD_SM_USERJOBORG
(
    USER_ID NUMBER(22) NOT NULL,
    JOB_ID VARCHAR2(50) NOT NULL,
    ORG_ID VARCHAR2(50) NOT NULL,
    SAME_JOB_USER_SN NUMBER(22),
    JOB_SN NUMBER(22),
    JOB_STARTTIME DATE,
    JOB_FETTLE NUMBER(22)
);

ALTER TABLE TD_SM_USERJOBORG
    ADD CONSTRAINT TD_SM_USERJOBORG_PK
PRIMARY KEY (USER_ID,JOB_ID,ORG_ID);






-----------------------------------------------------------------------------
-- TD_SM_USERROLE
-----------------------------------------------------------------------------
DROP TABLE TD_SM_USERROLE CASCADE CONSTRAINTS;

CREATE TABLE TD_SM_USERROLE
(
    USER_ID NUMBER(22) NOT NULL,
    ROLE_ID VARCHAR2(50) NOT NULL,
    RESOP_ORIGIN_USERID VARCHAR2(50) default '1'
);

ALTER TABLE TD_SM_USERROLE
    ADD CONSTRAINT TD_SM_USERROLE_PK
PRIMARY KEY (USER_ID,ROLE_ID);






-----------------------------------------------------------------------------
-- TD_SP_HOLIDAY
-----------------------------------------------------------------------------
DROP TABLE TD_SP_HOLIDAY CASCADE CONSTRAINTS;

CREATE TABLE TD_SP_HOLIDAY
(
    HOLIDAY VARCHAR2(10) NOT NULL,
    YHOLIDAY VARCHAR2(4) NOT NULL,
    MHOLIDAY VARCHAR2(2) NOT NULL,
    ORG_ID VARCHAR2(50)
);

ALTER TABLE TD_SP_HOLIDAY
    ADD CONSTRAINT TD_SP_HOLIDAY_PK
PRIMARY KEY (HOLIDAY,YHOLIDAY,MHOLIDAY);






-----------------------------------------------------------------------------
-- TD_SD_SCHEDULAR
-----------------------------------------------------------------------------
DROP TABLE TD_SD_SCHEDULAR CASCADE CONSTRAINTS;

CREATE TABLE TD_SD_SCHEDULAR
(
    SCHEDULAR_ID NUMBER(22) NOT NULL,
    PLANNER_ID NUMBER(22),
    EXECUTOR_ID NUMBER(22),
    REQUEST_ID NUMBER(22),
    TOPIC VARCHAR2(255),
    PLACE VARCHAR2(255),
    CONTENT VARCHAR2(1000),
    BEGINTIME DATE,
    ENDTIME DATE,
    TYPE VARCHAR2(255),
    ISPUBLICAFFAIR NUMBER(22),
    ESSENTIALITY VARCHAR2(255),
    ISHISTORY NUMBER(22),
    ISLEISURE NUMBER(22),
    STATUS NUMBER(22),
    ISOPEN NUMBER(22) default null,
    PARTNER VARCHAR2(255)
);

ALTER TABLE TD_SD_SCHEDULAR
    ADD CONSTRAINT TD_SD_SCHEDULAR_PK
PRIMARY KEY (SCHEDULAR_ID);






-----------------------------------------------------------------------------
-- TD_SM_DICTTYPE
-----------------------------------------------------------------------------
DROP TABLE TD_SM_DICTTYPE CASCADE CONSTRAINTS;

CREATE TABLE TD_SM_DICTTYPE
(
    DATA_VALIDATE_FIELD VARCHAR2(50),
    DATA_CREATE_ORGID_FIELD VARCHAR2(50),
    DICTTYPE_TYPE NUMBER(2),
    IS_TREE NUMBER(1) default 0,
    DICTTYPE_ID VARCHAR2(50) NOT NULL,
    USER_ID NUMBER(22),
    DICTTYPE_NAME VARCHAR2(100),
    DICTTYPE_DESC VARCHAR2(100),
    DICTTYPE_PARENT VARCHAR2(50),
    DATA_TABLE_NAME VARCHAR2(50),
    DATA_NAME_FILED VARCHAR2(50),
    DATA_VALUE_FIELD VARCHAR2(50),
    DATA_ORDER_FIELD VARCHAR2(50),
    DATA_TYPEID_FIELD VARCHAR2(50),
    DATA_DBNAME VARCHAR2(50),
    DATA_PARENTID_FIELD VARCHAR2(50),
    DATA_NAME_CN VARCHAR2(100) default '名称',
    DATA_VALUE_CN VARCHAR2(100) default '真实值',
    KEY_GENERAL_TYPE NUMBER(2),
    NAME_GENERAL_TYPE VARCHAR2(100),
    KEY_GENERAL_INFO VARCHAR2(100),
    NEEDCACHE NUMBER(1) default 1,
    ENABLE_VALUE_MODIFY NUMBER(1) default 0
);

ALTER TABLE TD_SM_DICTTYPE
    ADD CONSTRAINT TD_SM_DICTTYPE_PK
PRIMARY KEY (DICTTYPE_ID);






-----------------------------------------------------------------------------
-- esb_params
-----------------------------------------------------------------------------
DROP TABLE esb_params CASCADE CONSTRAINTS;

CREATE TABLE esb_params
(
    NODE_ID VARCHAR2(368) NOT NULL,
    NAME VARCHAR2(100) NOT NULL,
    VALUE VARCHAR2(100),
    PARAM_TYPE VARCHAR2(368) NOT NULL,
    ISBIGDATA NUMBER(20,0) default 0,
    BIGDATA BLOB,
    RN NUMBER(20,0) default 0 NOT NULL
);

ALTER TABLE esb_params
    ADD CONSTRAINT esb_params_PK
PRIMARY KEY (NODE_ID,NAME,PARAM_TYPE,RN);






-----------------------------------------------------------------------------
-- AGENT_WORKLOAD
-----------------------------------------------------------------------------
DROP TABLE AGENT_WORKLOAD CASCADE CONSTRAINTS;

CREATE TABLE AGENT_WORKLOAD
(
    AGENTID NUMBER(19),
    BUSINESSID VARCHAR2(200),
    BUSINESSNAME VARCHAR2(254),
    TASKNAME VARCHAR2(254),
    COMMITTIME DATE,
    RESULT VARCHAR2(256),
    PERFORMER VARCHAR2(32),
    NEXTPERFORMER VARCHAR2(32),
    EXT1 NUMBER(19),
    EXT2 VARCHAR2(32),
    EXT3 VARCHAR2(64)
);







-----------------------------------------------------------------------------
-- ASSIGNMENT_AGENT
-----------------------------------------------------------------------------
DROP TABLE ASSIGNMENT_AGENT CASCADE CONSTRAINTS;

CREATE TABLE ASSIGNMENT_AGENT
(
    ID NUMBER(19),
    CLIENT VARCHAR2(50),
    AGENT VARCHAR2(50),
    STARTTIME DATE,
    ENDTIME DATE,
    REALENDTIME DATE,
    PROCDEFID VARCHAR2(100)
);







-----------------------------------------------------------------------------
-- TB_SM_INPUTTYPE
-----------------------------------------------------------------------------
DROP TABLE TB_SM_INPUTTYPE CASCADE CONSTRAINTS;

CREATE TABLE TB_SM_INPUTTYPE
(
    INPUT_TYPE_ID NUMBER(5) NOT NULL,
    INPUT_TYPE_DESC VARCHAR2(200),
    DATASOURCE_PATH VARCHAR2(200),
    INPUT_TYPE_NAME VARCHAR2(200) NOT NULL,
    SCRIPT VARCHAR2(4000)
);

ALTER TABLE TB_SM_INPUTTYPE
    ADD CONSTRAINT TB_SM_INPUTTYPE_PK
PRIMARY KEY (INPUT_TYPE_ID);






-----------------------------------------------------------------------------
-- TD_SEC_SMS_INTERFACE
-----------------------------------------------------------------------------
DROP TABLE TD_SEC_SMS_INTERFACE CASCADE CONSTRAINTS;

CREATE TABLE TD_SEC_SMS_INTERFACE
(
    MESSAGE_ID VARCHAR2(20),
    CONTENT VARCHAR2(2000),
    DONETIME VARCHAR2(40),
    STATUS NUMBER(22) default 0,
    MESSAGE_TYPE NUMBER(22) default 0,
    SRCMOBILE VARCHAR2(20),
    DSTMOBILE VARCHAR2(40),
    WORKER_NAME VARCHAR2(40),
    ID NUMBER(22) NOT NULL,
    SENDTIME VARCHAR2(40),
    MEETINGID VARCHAR2(50),
    RETRY NUMBER(22) default 0
);







-----------------------------------------------------------------------------
-- TD_SM_DICATTACHFIELD
-----------------------------------------------------------------------------
DROP TABLE TD_SM_DICATTACHFIELD CASCADE CONSTRAINTS;

CREATE TABLE TD_SM_DICATTACHFIELD
(
    DICTTYPE_ID VARCHAR2(50),
    FIELD_NAME VARCHAR2(50),
    LABEL VARCHAR2(100),
    INPUT_TYPE_ID NUMBER(5),
    TABLE_COLUMN VARCHAR2(50),
    ISNULLABLE NUMBER(1),
    ISUNIQUE NUMBER(1) default 0,
    DATEFORMAT VARCHAR2(20),
    SN NUMBER(5) default 1
);







-----------------------------------------------------------------------------
-- TD_SM_GROUP
-----------------------------------------------------------------------------
DROP TABLE TD_SM_GROUP CASCADE CONSTRAINTS;

CREATE TABLE TD_SM_GROUP
(
    GROUP_ID NUMBER(22) NOT NULL,
    GROUP_NAME VARCHAR2(100),
    GROUP_DESC VARCHAR2(100),
    REMARK1 VARCHAR2(100),
    REMARK2 VARCHAR2(100),
    REMARK3 VARCHAR2(100),
    REMARK4 VARCHAR2(100),
    REMARK5 VARCHAR2(100),
    PARENT_ID NUMBER(22),
    GROUP_TREE_LEVEL VARCHAR2(200),
    OWNER_ID NUMBER(22) default 1
);

ALTER TABLE TD_SM_GROUP
    ADD CONSTRAINT TD_SM_GROUP_PK
PRIMARY KEY (GROUP_ID);






-----------------------------------------------------------------------------
-- TD_SM_INITYEAR_HOLIDAY
-----------------------------------------------------------------------------
DROP TABLE TD_SM_INITYEAR_HOLIDAY CASCADE CONSTRAINTS;

CREATE TABLE TD_SM_INITYEAR_HOLIDAY
(
    ORG_ID VARCHAR2(50),
    YHOLIDAY VARCHAR2(4) NOT NULL
);

ALTER TABLE TD_SM_INITYEAR_HOLIDAY
    ADD CONSTRAINT TD_SM_INITYEAR_HOLIDAY_PK
PRIMARY KEY (YHOLIDAY);






-----------------------------------------------------------------------------
-- TD_SM_JOB
-----------------------------------------------------------------------------
DROP TABLE TD_SM_JOB CASCADE CONSTRAINTS;

CREATE TABLE TD_SM_JOB
(
    JOB_ID VARCHAR2(50) NOT NULL,
    JOB_NAME VARCHAR2(100),
    JOB_DESC VARCHAR2(200),
    JOB_FUNCTION VARCHAR2(200),
    JOB_AMOUNT VARCHAR2(100),
    JOB_NUMBER VARCHAR2(100),
    JOB_CONDITION VARCHAR2(200),
    JOB_RANK VARCHAR2(100),
    OWNER_ID NUMBER(22) default 1
);

ALTER TABLE TD_SM_JOB
    ADD CONSTRAINT TD_SM_JOB_PK
PRIMARY KEY (JOB_ID);






-----------------------------------------------------------------------------
-- TD_SM_LOG
-----------------------------------------------------------------------------
DROP TABLE TD_SM_LOG CASCADE CONSTRAINTS;

CREATE TABLE TD_SM_LOG
(
    LOG_ID NUMBER(22) NOT NULL,
    LOG_OPERUSER VARCHAR2(50),
    OP_ORGID VARCHAR2(50),
    OPER_MODULE VARCHAR2(200),
    LOG_VISITORIAL VARCHAR2(200),
    LOG_OPERTIME DATE,
    LOG_CONTENT CLOB,
    REMARK1 VARCHAR2(100),
    OPER_TYPE NUMBER(1)
);

ALTER TABLE TD_SM_LOG
    ADD CONSTRAINT TD_SM_LOG_PK
PRIMARY KEY (LOG_ID);






-----------------------------------------------------------------------------
-- TD_SM_LOGMODULE
-----------------------------------------------------------------------------
DROP TABLE TD_SM_LOGMODULE CASCADE CONSTRAINTS;

CREATE TABLE TD_SM_LOGMODULE
(
    LOGMODULE VARCHAR2(50),
    STATUS NUMBER(22),
    MODULE_DESC VARCHAR2(50),
    ID VARCHAR2(50) NOT NULL
);

ALTER TABLE TD_SM_LOGMODULE
    ADD CONSTRAINT TD_SM_LOGMODULE_PK
PRIMARY KEY (ID);






-----------------------------------------------------------------------------
-- TD_SM_LOG_HIS
-----------------------------------------------------------------------------
DROP TABLE TD_SM_LOG_HIS CASCADE CONSTRAINTS;

CREATE TABLE TD_SM_LOG_HIS
(
    LOG_ID NUMBER(22) NOT NULL,
    LOG_OPERUSER VARCHAR2(50),
    OP_ORGID VARCHAR2(50),
    OPER_MODULE VARCHAR2(200),
    LOG_VISITORIAL VARCHAR2(200),
    LOG_OPERTIME DATE,
    LOG_CONTENT CLOB,
    REMARK1 VARCHAR2(100),
    OPER_TYPE NUMBER(1)
);

ALTER TABLE TD_SM_LOG_HIS
    ADD CONSTRAINT TD_SM_LOG_HIS_PK
PRIMARY KEY (LOG_ID);






-----------------------------------------------------------------------------
-- TD_SM_ORGANIZATION
-----------------------------------------------------------------------------
DROP TABLE TD_SM_ORGANIZATION CASCADE CONSTRAINTS;

CREATE TABLE TD_SM_ORGANIZATION
(
    ORG_ID VARCHAR2(50) NOT NULL,
    ORG_SN NUMBER(22) NOT NULL,
    ORG_NAME VARCHAR2(40) NOT NULL,
    PARENT_ID VARCHAR2(100) NOT NULL,
    PATH VARCHAR2(1000),
    LAYER VARCHAR2(200),
    CHILDREN VARCHAR2(1000),
    CODE VARCHAR2(100),
    JP VARCHAR2(40),
    QP VARCHAR2(40),
    CREATINGTIME DATE,
    CREATOR VARCHAR2(100) default '1


',
    ORGNUMBER VARCHAR2(100),
    ORGDESC VARCHAR2(300),
    REMARK1 VARCHAR2(100),
    REMARK2 VARCHAR2(100),
    REMARK3 VARCHAR2(100),
    REMARK4 VARCHAR2(100),
    REMARK5 VARCHAR2(100),
    CHARGEORGID VARCHAR2(50),
    ISPARTYBUSSINESS NUMBER(1) default 1,
    SATRAPJOBID VARCHAR2(50),
    ORG_LEVEL VARCHAR2(1) default '1',
    ORG_XZQM VARCHAR2(10),
    ORG_TREE_LEVEL VARCHAR2(100),
    ISDIRECTLYPARTY NUMBER(1) default 0,
    ISFOREIGNPARTY NUMBER(1) default 0,
    ISJICHAPARTY NUMBER(1) default 0,
    ISDIRECTGUANHU NUMBER(1) default 0
);

ALTER TABLE TD_SM_ORGANIZATION
    ADD CONSTRAINT TD_SM_ORGANIZATION_PK
PRIMARY KEY (ORG_ID);






-----------------------------------------------------------------------------
-- TD_SM_PERMISSION_ORIGINE
-----------------------------------------------------------------------------
DROP TABLE TD_SM_PERMISSION_ORIGINE CASCADE CONSTRAINTS;

CREATE TABLE TD_SM_PERMISSION_ORIGINE
(
    ORIGINE_TYPE VARCHAR2(50) NOT NULL,
    ORIGINE_ID VARCHAR2(20) NOT NULL,
    OP_ID VARCHAR2(50) NOT NULL,
    RES_ID VARCHAR2(100) NOT NULL,
    ROLE_ID VARCHAR2(50) NOT NULL,
    RESTYPE_ID VARCHAR2(50) NOT NULL,
    TYPES VARCHAR2(50) NOT NULL
);

ALTER TABLE TD_SM_PERMISSION_ORIGINE
    ADD CONSTRAINT TD_SM_PERMISSION_ORIGINE_PK
PRIMARY KEY (ORIGINE_TYPE,ORIGINE_ID,OP_ID,RES_ID,ROLE_ID,RESTYPE_ID,TYPES);






-----------------------------------------------------------------------------
-- TD_SM_RES
-----------------------------------------------------------------------------
DROP TABLE TD_SM_RES CASCADE CONSTRAINTS;

CREATE TABLE TD_SM_RES
(
    RES_ID VARCHAR2(50) NOT NULL,
    RESTYPE_ID VARCHAR2(50),
    TITLE VARCHAR2(500),
    ROLE_USAGE VARCHAR2(1),
    PARENT_ID VARCHAR2(50),
    PATH VARCHAR2(1000),
    MARKER VARCHAR2(200),
    RESERVED1 VARCHAR2(200),
    RESERVED3 VARCHAR2(200),
    RESERVED4 VARCHAR2(200),
    RESERVED5 VARCHAR2(200),
    ATTR1 VARCHAR2(200),
    ATTR2 VARCHAR2(200),
    ATTR3 VARCHAR2(200),
    ATTR4 VARCHAR2(200),
    ATTR5 VARCHAR2(200),
    ATTR6 VARCHAR2(200),
    ATTR7 VARCHAR2(200),
    ATTR8 VARCHAR2(200),
    ATTR9 VARCHAR2(200),
    ATTR10 VARCHAR2(200),
    ATTR11 VARCHAR2(200),
    ATTR12 VARCHAR2(200),
    ATTR13 VARCHAR2(200),
    ATTR14 VARCHAR2(200),
    ATTR15 VARCHAR2(200),
    ATTR16 VARCHAR2(200),
    ATTR17 VARCHAR2(200),
    ATTR18 VARCHAR2(200),
    ATTR19 VARCHAR2(200),
    ATTR20 VARCHAR2(200),
    ATTR21 VARCHAR2(200),
    ATTR22 VARCHAR2(200),
    ATTR23 VARCHAR2(200),
    ATTR24 VARCHAR2(200),
    ATTR25 VARCHAR2(200),
    ATTR26 VARCHAR2(200) default '0',
    ATTR27 VARCHAR2(1000)
);

ALTER TABLE TD_SM_RES
    ADD CONSTRAINT TD_SM_RES_PK
PRIMARY KEY (RES_ID);






-----------------------------------------------------------------------------
-- TD_SM_ROLE
-----------------------------------------------------------------------------
DROP TABLE TD_SM_ROLE CASCADE CONSTRAINTS;

CREATE TABLE TD_SM_ROLE
(
    ROLE_ID VARCHAR2(50) NOT NULL,
    ROLE_NAME VARCHAR2(100) NOT NULL,
    ROLE_TYPE VARCHAR2(100),
    ROLE_DESC VARCHAR2(1024),
    ROLE_USAGE VARCHAR2(1),
    REMARK1 VARCHAR2(100),
    REMARK2 VARCHAR2(100),
    REMARK3 VARCHAR2(100),
    OWNER_ID NUMBER(22) default 1
);

ALTER TABLE TD_SM_ROLE
    ADD CONSTRAINT TD_SM_ROLE_PK
PRIMARY KEY (ROLE_ID);






-----------------------------------------------------------------------------
-- TD_SM_ROLERESOP
-----------------------------------------------------------------------------
DROP TABLE TD_SM_ROLERESOP CASCADE CONSTRAINTS;

CREATE TABLE TD_SM_ROLERESOP
(
    OP_ID VARCHAR2(50) NOT NULL,
    RES_ID VARCHAR2(100) NOT NULL,
    ROLE_ID VARCHAR2(50) NOT NULL,
    RESTYPE_ID VARCHAR2(50) NOT NULL,
    AUTO VARCHAR2(50),
    RES_NAME VARCHAR2(500),
    TYPES VARCHAR2(50) NOT NULL,
    AUTHORIZATION_TYPE NUMBER(22) default 0,
    USE_COUNT NUMBER(22),
    AUTHORIZATION_STIME DATE default sysdate,
    AUTHORIZATION_ETIME DATE,
    USE_COUNTED NUMBER(22)
);

ALTER TABLE TD_SM_ROLERESOP
    ADD CONSTRAINT TD_SM_ROLERESOP_PK
PRIMARY KEY (OP_ID,RES_ID,ROLE_ID,RESTYPE_ID,TYPES);






-----------------------------------------------------------------------------
-- TD_SM_ROLETYPE
-----------------------------------------------------------------------------
DROP TABLE TD_SM_ROLETYPE CASCADE CONSTRAINTS;

CREATE TABLE TD_SM_ROLETYPE
(
    TYPE_NAME VARCHAR2(100),
    TYPE_DESC VARCHAR2(500),
    TYPE_ID NUMBER(22) NOT NULL,
    CREATOR_USER_ID VARCHAR2(20) default '1

',
    CREATOR_ORG_ID VARCHAR2(20) default '1

'
);

ALTER TABLE TD_SM_ROLETYPE
    ADD CONSTRAINT TD_SM_ROLETYPE_PK
PRIMARY KEY (TYPE_ID);






-----------------------------------------------------------------------------
-- TD_SM_USER
-----------------------------------------------------------------------------
DROP TABLE TD_SM_USER CASCADE CONSTRAINTS;

CREATE TABLE TD_SM_USER
(
    USER_ID NUMBER(22) NOT NULL,
    USER_SN NUMBER(22) NOT NULL,
    USER_NAME VARCHAR2(200) NOT NULL,
    USER_PASSWORD VARCHAR2(40) NOT NULL,
    USER_REALNAME VARCHAR2(100) NOT NULL,
    USER_PINYIN VARCHAR2(100),
    USER_SEX VARCHAR2(100),
    USER_HOMETEL VARCHAR2(100),
    USER_WORKTEL VARCHAR2(100),
    USER_WORKNUMBER VARCHAR2(100),
    USER_MOBILETEL1 VARCHAR2(100),
    USER_MOBILETEL2 VARCHAR2(100),
    USER_FAX VARCHAR2(100),
    USER_OICQ VARCHAR2(100),
    USER_BIRTHDAY DATE,
    USER_EMAIL VARCHAR2(100),
    USER_ADDRESS VARCHAR2(200),
    USER_POSTALCODE VARCHAR2(10),
    USER_IDCARD VARCHAR2(50),
    USER_ISVALID NUMBER(22),
    USER_REGDATE DATE,
    USER_LOGINCOUNT NUMBER(22),
    USER_TYPE VARCHAR2(100),
    REMARK1 VARCHAR2(100),
    REMARK2 VARCHAR2(100),
    REMARK3 VARCHAR2(100),
    REMARK4 VARCHAR2(100),
    REMARK5 VARCHAR2(100),
    PAST_TIME DATE,
    DREDGE_TIME VARCHAR2(50),
    LASTLOGIN_DATE DATE,
    WORKLENGTH VARCHAR2(50),
    POLITICS VARCHAR2(100),
    ISTAXMANAGER NUMBER(1),
    LOGON_IP VARCHAR2(15),
    CERT_SN VARCHAR2(50)
);

ALTER TABLE TD_SM_USER
    ADD CONSTRAINT TD_SM_USER_PK
PRIMARY KEY (USER_ID);






-----------------------------------------------------------------------------
-- TD_SM_USERGROUP
-----------------------------------------------------------------------------
DROP TABLE TD_SM_USERGROUP CASCADE CONSTRAINTS;

CREATE TABLE TD_SM_USERGROUP
(
    GROUP_ID NUMBER(22) NOT NULL,
    USER_ID NUMBER(22) NOT NULL
);

ALTER TABLE TD_SM_USERGROUP
    ADD CONSTRAINT TD_SM_USERGROUP_PK
PRIMARY KEY (GROUP_ID,USER_ID);






-----------------------------------------------------------------------------
-- TD_SM_USERJOBORG_HISTORY
-----------------------------------------------------------------------------
DROP TABLE TD_SM_USERJOBORG_HISTORY CASCADE CONSTRAINTS;

CREATE TABLE TD_SM_USERJOBORG_HISTORY
(
    USER_ID NUMBER(22) NOT NULL,
    JOB_ID VARCHAR2(50) NOT NULL,
    JOB_NAME VARCHAR2(100) NOT NULL,
    ORG_ID VARCHAR2(50) NOT NULL,
    ORG_NAME VARCHAR2(100) NOT NULL,
    JOB_STARTTIME DATE,
    JOB_QUASHTIME DATE,
    JOB_FETTLE NUMBER(22)
);







-----------------------------------------------------------------------------
-- V_TB_RES_ORG_USER_WRITE
-----------------------------------------------------------------------------
DROP TABLE V_TB_RES_ORG_USER_WRITE CASCADE CONSTRAINTS;

CREATE TABLE V_TB_RES_ORG_USER_WRITE
(
    USER_ID VARCHAR2(50) NOT NULL,
    ORG_ID VARCHAR2(100) NOT NULL
);






ALTER TABLE TD_REMINDINFO
    ADD CONSTRAINT TD_REMINDINFO_FK_1 FOREIGN KEY (USER_ID)
    REFERENCES TD_SM_USER (USER_ID)
;



ALTER TABLE TD_SD_NOTEPAPER
    ADD CONSTRAINT TD_SD_NOTEPAPER_FK_1 FOREIGN KEY (USER_ID)
    REFERENCES TD_SM_USER (USER_ID)
;



ALTER TABLE TD_SD_NOTIC
    ADD CONSTRAINT TD_SD_NOTIC_FK_1 FOREIGN KEY (NOTIC_PLANNER_ID)
    REFERENCES TD_SM_USER (USER_ID)
;

ALTER TABLE TD_SD_NOTIC
    ADD CONSTRAINT TD_SD_NOTIC_FK_2 FOREIGN KEY (EXECUTOR_ID)
    REFERENCES TD_SM_USER (USER_ID)
;



ALTER TABLE TD_SD_RATIFYADVICE
    ADD CONSTRAINT TD_SD_RATIFYADVICE_FK_1 FOREIGN KEY (RATIFIER_ID)
    REFERENCES TD_SM_USER (USER_ID)
;

ALTER TABLE TD_SD_RATIFYADVICE
    ADD CONSTRAINT TD_SD_RATIFYADVICE_FK_2 FOREIGN KEY (SCHEDULAR_ID)
    REFERENCES TD_SD_SCHEDULAR (SCHEDULAR_ID)
;



ALTER TABLE TD_SD_REMIND
    ADD CONSTRAINT TD_SD_REMIND_FK_1 FOREIGN KEY (SCHEDULAR_ID)
    REFERENCES TD_SD_SCHEDULAR (SCHEDULAR_ID)
;



ALTER TABLE TD_SD_SHARE
    ADD CONSTRAINT TD_SD_SHARE_FK_1 FOREIGN KEY (VIEWUSER_ID)
    REFERENCES TD_SM_USER (USER_ID)
;

ALTER TABLE TD_SD_SHARE
    ADD CONSTRAINT TD_SD_SHARE_FK_2 FOREIGN KEY (SCHEDULAR_ID)
    REFERENCES TD_SD_SCHEDULAR (SCHEDULAR_ID)
;



ALTER TABLE TD_SM_DICTDATA
    ADD CONSTRAINT TD_SM_DICTDATA_FK_1 FOREIGN KEY (DICTTYPE_ID)
    REFERENCES TD_SM_DICTTYPE (DICTTYPE_ID)
;



ALTER TABLE TD_SM_DICTKEYWORDS
    ADD CONSTRAINT TD_SM_DICTKEYWORDS_FK_1 FOREIGN KEY (DICTTYPE_ID)
    REFERENCES TD_SM_DICTTYPE (DICTTYPE_ID)
;



ALTER TABLE TD_SM_GROUPROLE
    ADD CONSTRAINT TD_SM_GROUPROLE_FK_1 FOREIGN KEY (ROLE_ID)
    REFERENCES TD_SM_ROLE (ROLE_ID)
;



ALTER TABLE TD_SM_LOGDETAIL
    ADD CONSTRAINT TD_SM_LOGDETAIL_FK_1 FOREIGN KEY (LOG_ID)
    REFERENCES TD_SM_LOG (LOG_ID)
;



ALTER TABLE TD_SM_LOGDETAIL_HIS
    ADD CONSTRAINT TD_SM_LOGDETAIL_HIS_FK_1 FOREIGN KEY (LOG_ID)
    REFERENCES TD_SM_LOG_HIS (LOG_ID)
;



ALTER TABLE TD_SM_ORGJOB
    ADD CONSTRAINT TD_SM_ORGJOB_FK_1 FOREIGN KEY (JOB_ID)
    REFERENCES TD_SM_JOB (JOB_ID)
;



ALTER TABLE TD_SM_ORGJOBROLE
    ADD CONSTRAINT TD_SM_ORGJOBROLE_FK_1 FOREIGN KEY (ROLE_ID)
    REFERENCES TD_SM_ROLE (ROLE_ID)
;

ALTER TABLE TD_SM_ORGJOBROLE
    ADD CONSTRAINT TD_SM_ORGJOBROLE_FK_2 FOREIGN KEY (ORG_ID)
    REFERENCES TD_SM_ORGANIZATION (ORG_ID)
;

ALTER TABLE TD_SM_ORGJOBROLE
    ADD CONSTRAINT TD_SM_ORGJOBROLE_FK_3 FOREIGN KEY (JOB_ID)
    REFERENCES TD_SM_JOB (JOB_ID)
;



ALTER TABLE TD_SM_ORGMANAGER
    ADD CONSTRAINT TD_SM_ORGMANAGER_FK_1 FOREIGN KEY (USER_ID)
    REFERENCES TD_SM_USER (USER_ID)
;

ALTER TABLE TD_SM_ORGMANAGER
    ADD CONSTRAINT TD_SM_ORGMANAGER_FK_2 FOREIGN KEY (ORG_ID)
    REFERENCES TD_SM_ORGANIZATION (ORG_ID)
;



ALTER TABLE TD_SM_ORGROLE
    ADD CONSTRAINT TD_SM_ORGROLE_FK_1 FOREIGN KEY (ROLE_ID)
    REFERENCES TD_SM_ROLE (ROLE_ID)
;



ALTER TABLE TD_SM_ORGUSER
    ADD CONSTRAINT TD_SM_ORGUSER_FK_1 FOREIGN KEY (USER_ID)
    REFERENCES TD_SM_USER (USER_ID)
;

ALTER TABLE TD_SM_ORGUSER
    ADD CONSTRAINT TD_SM_ORGUSER_FK_2 FOREIGN KEY (ORG_ID)
    REFERENCES TD_SM_ORGANIZATION (ORG_ID)
;



ALTER TABLE TD_SM_TAXCODE_ORGANIZATION
    ADD CONSTRAINT TD_SM_TAXCODE_ORGANIZATIO_FK_1 FOREIGN KEY (DICTTYPE_ID)
    REFERENCES TD_SM_DICTTYPE (DICTTYPE_ID)
;

ALTER TABLE TD_SM_TAXCODE_ORGANIZATION
    ADD CONSTRAINT TD_SM_TAXCODE_ORGANIZATIO_FK_2 FOREIGN KEY (ORG_ID)
    REFERENCES TD_SM_ORGANIZATION (ORG_ID)
;



ALTER TABLE TD_SM_USERJOBORG
    ADD CONSTRAINT TD_SM_USERJOBORG_FK_1 FOREIGN KEY (JOB_ID)
    REFERENCES TD_SM_JOB (JOB_ID)
;



ALTER TABLE TD_SM_USERROLE
    ADD CONSTRAINT TD_SM_USERROLE_FK_1 FOREIGN KEY (ROLE_ID)
    REFERENCES TD_SM_ROLE (ROLE_ID)
;



ALTER TABLE TD_SP_HOLIDAY
    ADD CONSTRAINT TD_SP_HOLIDAY_FK_1 FOREIGN KEY (ORG_ID)
    REFERENCES TD_SM_ORGANIZATION (ORG_ID)
;



ALTER TABLE TD_SD_SCHEDULAR
    ADD CONSTRAINT TD_SD_SCHEDULAR_FK_1 FOREIGN KEY (EXECUTOR_ID)
    REFERENCES TD_SM_USER (USER_ID)
;

ALTER TABLE TD_SD_SCHEDULAR
    ADD CONSTRAINT TD_SD_SCHEDULAR_FK_2 FOREIGN KEY (PLANNER_ID)
    REFERENCES TD_SM_USER (USER_ID)
;



ALTER TABLE TD_SM_DICTTYPE
    ADD CONSTRAINT TD_SM_DICTTYPE_FK_1 FOREIGN KEY (USER_ID)
    REFERENCES TD_SM_USER (USER_ID)
;















































